gword = [{text: 'Malaysia', size: 100},
{text: '', size: 64},
{text: 'Singapore', size: 60},
{text: 'Australia', size: 56},
{text: 'Thailand', size: 40},
{text: 'Indonesia', size: 28},
{text: 'Germany', size: 28},
{text: 'United Kingdom', size: 28},
{text: 'USA', size: 28},
{text: 'Italy', size: 28},
{text: 'France', size: 24},
{text: 'Taiwan', size: 24},
{text: 'England', size: 20},
{text: 'UK', size: 20},
{text: 'Ferrero S.p.A.,P.le P. Ferrero 1 - 12051 - Alba (CN),Italia', size: 20},
{text: 'Spain', size: 20},
{text: 'Ciudad de México,México', size: 20},
{text: 'Philippines', size: 20},
{text: 'Denmark', size: 20},
{text: 'Ireland', size: 20},
{text: 'Belgium', size: 20},
{text: 'China', size: 20},
{text: 'Vietnam', size: 20},
{text: 'Korea', size: 20},
{text: 'Fremont,Miami,Estados Unidos', size: 20}
];
