gword = [{text: 'Singapore', size: 100},
{text: 'Malaysia', size: 68},
{text: 'China', size: 41},
{text: 'Thailand', size: 39},
{text: 'Australia', size: 34},
{text: 'United States', size: 30},
{text: '', size: 25},
{text: 'Taiwan', size: 24},
{text: 'Germany', size: 22},
{text: 'Japan', size: 21},
{text: 'Italy', size: 21},
{text: 'Indonesia', size: 21},
{text: 'USA', size: 20},
{text: 'E.U', size: 20},
{text: 'New Zealand', size: 20},
{text: 'India', size: 20},
{text: 'Philipines', size: 20},
{text: 'England', size: 20},
{text: 'Oregon', size: 20},
{text: 'Denmark', size: 20},
{text: 'Amsterdam', size: 20},
{text: 'Sweden', size: 20},
{text: 'holland', size: 20},
{text: 'Chile', size: 20},
{text: 'United Kingdom', size: 20},
{text: 'Spain', size: 20},
{text: 'Modena, Italy', size: 20},
{text: 'Philippines', size: 20},
{text: 'Pakistan', size: 20},
{text: 'Brazil', size: 20},
{text: 'Vietnam', size: 20}
];
